server:
  port: 8091
  servlet:
    context-path: ${customs.content.path}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  redis:
    host: ${redis.server.url}
    port: ${redis.server.port}
    password: ${redis.server.password}
    timeout: 2000s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://${jayud.datasource.ip}:${jayud.datasource.port}/${business.customs.datasource.name}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: ${jayud.datasource.username}
      password: ${jayud.datasource.password}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
mybatis-plus:
  mapper-locations: classpath:com.jayud.customs.mapper/*.xml
  typeAliasesPackage: com.jayud.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
swagger:
  enable: true
logging:
  path: /data/log/customs
feign:
  httpclient:
    connection-timeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
