server:
  port: 9001
vivo:
  default:
    username: JAYUD
    password: 123456
    scope: e5b2032e5713418699b020c8d6d007e8
  urls:
    token: https://egtm.vivo.xyz:9976/token
  public-key: <RSAKeyValue><Modulus>4xGrWUFEftqNS4DvSOW9wfeYK1i9gJBYB+tmhz6E9QCo6cvRdmT+IaG6lE6U7sh1dP3atLc8lzvljDmxoDu/SBMLkDXiXJgj7AJWbhDUn1xCbQb/1jEb08jEqr/3K4+03bCX06W0V5HrjL53GiQ0dZHIO1eFdAvRDPYfvIwIWq0=</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>