package com.jayud.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 时间紧急，名字，message 需要更改
 */
@AllArgsConstructor
@Getter
public enum VivoFileTypeEnum {

    SIMPLEDTLEXCEL(1),
    SHIPPINGBILLEXCEL(2),
    PROFORMAINVOICEEXCEL(3),
    PROFORMAINVOICEPDF(4),
    COMMERCIALINVOICEEXCEL(5),
    COMMERCIALINVOICEPDF(6),
    COMMERCIALINVOICEPDF7(7),
    COMMERCIALINVOICEPDF8(8),
    COMMERCIALINVOICEPDF9(9),
    COMMERCIALINVOICEPDF10(10),
    COMMERCIALINVOICEPDF11(11),
    COMMERCIALINVOICEPDF12(12),
    COMMERCIALINVOICEPDF13(13),
    COMMERCIALINVOICEPDF14(14),
    COMMERCIALINVOICEPDF15(15),
    COMMERCIALINVOICEPDF16(16),
    COMMERCIALINVOICEPDF17(17),
    COMMERCIALINVOICEPDF18(18),
    COMMERCIALINVOICEPDF19(19),
    COMMERCIALINVOICEPDF20(20),
    COMMERCIALINVOICEPDF21(21),
    COMMERCIALINVOICEPDF22(22),
    COMMERCIALINVOICEPDF23(23),
    COMMERCIALINVOICEPDF24(24),
    COMMERCIALINVOICEPDF25(25),
    COMMERCIALINVOICEPDF26(26),
    COMMERCIALINVOICEPDF27(27),
    COMMERCIALINVOICEPDF28(28),
    COMMERCIALINVOICEPDF29(29),
    COMMERCIALINVOICEPDF30(30),
    COMMERCIALINVOICEPDF31(31),
    COMMERCIALINVOICEPDF32(32),
    ;
    private Integer code;
}
