CREATE TABLE `void_billing_records` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `main_order_no` varchar(100) NOT NULL COMMENT '主订单编号',
  `order_no` varchar(100) DEFAULT NULL COMMENT '子订单号',
  `bill_id` bigint(20) DEFAULT NULL COMMENT '账单ID',
  `account_term` varchar(7) DEFAULT NULL COMMENT '核算期 XXXX-XX',
  `settlement_currency` varchar(10) DEFAULT NULL COMMENT '结算币种',
  `bill_no` varchar(100) NOT NULL COMMENT '账单编号',
  `make_user` varchar(20) NOT NULL COMMENT '生成账单人',
  `make_time` timestamp NULL DEFAULT NULL COMMENT '生成账单时间',
  `audit_user` varchar(20) DEFAULT NULL COMMENT '审核人',
  `audit_time` timestamp NULL DEFAULT NULL COMMENT '审核时间',
  `apply_status` varchar(10) DEFAULT '0' COMMENT '开票状态 0-未申请  1-待审核 2-审核通过 3-审核驳回',
  `invoice_amount` decimal(10,4) DEFAULT NULL COMMENT '开票金额',
  `audit_status` varchar(20) NOT NULL COMMENT '审核状态',
  `created_order_time` date NOT NULL COMMENT '建单日期',
  `cost_id` bigint(20) NOT NULL COMMENT '应收费用ID',
  `local_amount` decimal(10,4) DEFAULT NULL COMMENT '费用类型/类别/名称维度的本币金额',
  `remarks` varchar(200) DEFAULT NULL COMMENT '费用维度的备注',
  `created_user` varchar(20) DEFAULT NULL COMMENT '创建人',
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_user` varchar(20) DEFAULT NULL COMMENT '修改人',
  `updated_time` timestamp NULL DEFAULT NULL COMMENT '修改时间',
  `cost_info_name` varchar(20) DEFAULT NULL COMMENT '费用项',
  `money` decimal(10,4) DEFAULT NULL COMMENT '结算金额',
  `local_money_rate` decimal(10,4) DEFAULT NULL COMMENT '本币汇率',
  `cost_type` char(1) DEFAULT NULL COMMENT '费用类型(0-应收, 1-应付)',
  `current_currency_code` varchar(255) DEFAULT NULL COMMENT '当前币种',
  `exchange_rate` decimal(10,4) DEFAULT NULL COMMENT '结算汇率',
  `is_custom_exchange_rate` tinyint(1) DEFAULT NULL COMMENT '是否自定汇率',
  `operator` varchar(50) DEFAULT NULL COMMENT '操作人',
  `operation_time` datetime DEFAULT NULL COMMENT '操作时间',
  `legal_name` varchar(50) DEFAULT NULL COMMENT '法人主体姓名',
  `customer_name` varchar(100) DEFAULT NULL COMMENT '结算单位/供应商名称',
  `amount` decimal(10,4) DEFAULT NULL COMMENT '应收/应付金额(录用费用金额)',
  `sub_type` varchar(10) DEFAULT NULL COMMENT '如果是已子订单维度出账的,则记录具体的子订单类型',
  `is_sum_to_main` tinyint(1) DEFAULT NULL COMMENT '是否汇总到主订单',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COMMENT='作废账单表';