#数据库配置
jayud:
  datasource:
    ip: 192.168.0.231
    username: root
    password: Root!!2020
swagger:
  is:
    enable: true
#oms前缀路径
oms:
  content:
    path: /spider
#redis数据源
redis:
  server:
    url: 127.0.0.1
    port: 6379
    password: