CREATE TABLE `profit_statement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `main_order_no` varchar(200) DEFAULT NULL COMMENT '主订单编号',
  `order_no` varchar(200) DEFAULT NULL COMMENT '子订单编号',
  `is_main` tinyint(2) DEFAULT NULL COMMENT '是否主订单',
  `biz_type` varchar(50) DEFAULT NULL COMMENT '业务类型',
  `legal_name` varchar(500) DEFAULT NULL COMMENT '法人名称',
  `legal_id` bigint(20) DEFAULT NULL COMMENT '法人id',
  `department` varchar(50) DEFAULT NULL COMMENT '操作部门',
  `department_id` bigint(20) DEFAULT NULL COMMENT '操作部门id',
  `customer_name` varchar(500) DEFAULT NULL COMMENT '客户名称',
  `unit_code` varchar(100) DEFAULT NULL COMMENT '结算单位代码',
  `unit_name` varchar(500) DEFAULT NULL COMMENT '结算单位名称',
  `biz_uname` varchar(50) DEFAULT NULL COMMENT '业务员名称',
  `create_user` varchar(50) DEFAULT NULL COMMENT '创建人(登录用户)',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `re_amount` varchar(255) DEFAULT NULL COMMENT '应收金额(不包含内部)',
  `re_equivalent_amount` decimal(50,4) DEFAULT NULL COMMENT '应收折合金额(RMB)(不包含内部)',
  `pay_amount` varchar(255) DEFAULT NULL COMMENT '应付金额(不包含内部)',
  `pay_equivalent_amount` decimal(50,4) DEFAULT NULL COMMENT '应付折合金额(RMB)(不包含内部)',
  `profit` decimal(50,4) DEFAULT NULL COMMENT '利润(不包含内部)',
  `re_in_amount` varchar(255) DEFAULT NULL COMMENT '应收金额(内部)',
  `re_in_equivalent_amount` decimal(50,4) DEFAULT NULL COMMENT '应收折合金额(RMB)(内部)',
  `pay_in_amount` varchar(255) DEFAULT NULL COMMENT '应付金额(内部)',
  `pay_in_equivalent_amount` decimal(50,4) DEFAULT NULL COMMENT '应付折合金额(RMB)(内部)',
  `in_profit` decimal(50,4) DEFAULT NULL COMMENT '利润(包含内部)',
  `sync_time` datetime DEFAULT NULL COMMENT '同步时间',
  `re_cost_ids` varchar(500) DEFAULT NULL COMMENT '应收费用id集合(多个逗号隔开)',
  `pay_cost_ids` varchar(500) DEFAULT NULL COMMENT '应付费用id集合(多个逗号隔开)',
  `re_in_cost_ids` varchar(500) DEFAULT NULL COMMENT '应收费用id集合(多个逗号隔开)(内部)',
  `pay_in_cost_ids` varchar(500) DEFAULT NULL COMMENT '应付费用id集合(多个逗号隔开)(内部)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COMMENT='利润报表';