CREATE TABLE `customer_address` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '地址id',
  `type` int(10) NOT NULL COMMENT '地址类型（0 提货地址 1送货地址）',
  `customer_id` bigint(20) NOT NULL COMMENT '客户id',
  `contacts` varchar(50) NOT NULL COMMENT '联系人',
  `phone` varchar(20) NOT NULL COMMENT '联系电话',
  `province` bigint(20) NOT NULL COMMENT '省主键',
  `city` bigint(20) NOT NULL COMMENT '市主键',
  `area` bigint(20) DEFAULT NULL COMMENT '区主键',
  `address` varchar(100) NOT NULL COMMENT '详细地址',
  `post_code` varchar(20) DEFAULT NULL COMMENT '邮编',
  `status` int(1) DEFAULT '1' COMMENT '状态（0禁用 1启用）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(50) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_user` varchar(50) DEFAULT NULL COMMENT '更新人',
  `baidu_la_and_lo` varchar(100) DEFAULT NULL COMMENT '百度经纬度',
  `province_code` varchar(20) NOT NULL COMMENT '省code',
  `city_code` varchar(20) NOT NULL COMMENT '市code',
  `area_code` varchar(20) DEFAULT NULL COMMENT '区code',
  `final_address` varchar(500) NOT NULL COMMENT '最终地址',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='客户地址';