security:
  oauth2:
    client:
      clientId: jayud-system-web
      clientSecret: 123456
      accessTokenUri: http://127.0.0.1:10004/auth/oauth/token
      #accessTokenUri: http://192.168.3.39:10004/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://127.0.0.1:10004/auth/sysUser/current

server:
  servlet:
    context-path: /system-web
  port: 10114


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
    mongo:
      enabled: false
    mail:
      enabled: false

redis:
  server:
    url: 127.0.0.1
    port: 6379
    password: 'root'

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.100.140.250:8097/jayud_wms_ms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Jayud2021!@#
    # url: jdbc:mysql://113.100.140.250:6306/jayud-wms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # username: root
    # password: 123456
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      #login-username: admin
      #login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

#mybatis plus 设置org/jyd/**/mapper/xml/*Mapper.xml
mybatis-plus:
  type-aliases-package: com.jayud.**.entity
  mapper-locations: classpath*:/com/jayud/**/mapper/**/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
