CREATE TABLE `customs_questionnaire` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `customer_name` varchar(255) NOT NULL COMMENT '客户名称',
  `customer_code` varchar(50) NOT NULL COMMENT '客户代码',
  `customer_addr` varchar(255) DEFAULT NULL COMMENT '客户地址',
  `legal_representative` varchar(50) DEFAULT NULL COMMENT '法定代表人',
  `customer_type` int(11) DEFAULT NULL COMMENT '客户类型',
  `registered_capital` decimal(20,4) DEFAULT NULL COMMENT '注册资本(单位:万)',
  `phone` varchar(255) DEFAULT NULL COMMENT '联系人电话',
  `contacts` varchar(255) DEFAULT NULL COMMENT '联系人',
  `national_credit` int(11) DEFAULT '1' COMMENT '国家征信(0:异常,1:非异常)',
  `customs_credit` int(11) DEFAULT '1' COMMENT '海关征信(0:异常,1:非异常)',
  `payment_period` varchar(255) DEFAULT NULL COMMENT '承诺付款账期',
  `self_accounting` tinyint(4) DEFAULT NULL COMMENT '是否为自理记账',
  `is_alarm_system` int(10) DEFAULT NULL COMMENT '是否装警报系统(0:达标,1:部分达标,2:不达标)',
  `is_empe_iden_sys` int(10) DEFAULT NULL COMMENT '是否装员工识别系统(0:达标,1:部分达标,2:不达标)',
  `is_work_handover` int(10) DEFAULT NULL COMMENT '是否有要求工作交接(0:达标,1:部分达标,2:不达标)',
  `is_bus_partner_comp_eval` int(10) DEFAULT NULL COMMENT '是否对商业伙伴进行全面评价(0:达标,1:部分达标,2:不达标)',
  `is_goods_identical` int(10) DEFAULT NULL COMMENT '是否核对货物与单证信息的一致性(0:达标,1:部分达标,2:不达标)',
  `is_provide_vehicle_info` int(10) DEFAULT NULL COMMENT '是否提供车辆及司机信息(0:达标,1:部分达标,2:不达标)',
  `risk_level` int(10) DEFAULT NULL COMMENT '风险等级(1:不可接受之信用风险,2:高度信用风险,3:中度信用风险,4:低信用风险)',
  `recorder` varchar(50) DEFAULT NULL COMMENT '记录人',
  `evaluation_date` datetime DEFAULT NULL COMMENT '评估日期',
  `expires_time` datetime DEFAULT NULL COMMENT '失效时间',
  `status` int(5) DEFAULT '0' COMMENT '状态(0:待审核,1:经理审核,2:总经理审核)',
  `type` int(5) DEFAULT '0' COMMENT '类型(0:客户,1:供应商)',
  `update_user` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `audit_opinion` varchar(255) DEFAULT NULL COMMENT '审核意见',
  `is_edit` tinyint(2) DEFAULT NULL COMMENT '是否可编辑',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='海关调查问卷';